### ISSUE TITLE
Ignored </think>

### ISSUE THREAD

**Issue by Dariton4000** [lmstudio-ai/lmstudio-bug-tracker#482]
**Which version of LM Studio?**
LM Studio Beta 0.3.11

**Which operating system?**
Windows 11

**What is the bug?**
LM-Studio failed to exit the Thinking UI after encountering a </think> tag. The UI did not exit the "thinking" state.

**Screenshots**

ignored </think>:
![Image](https://github.com/user-attachments/assets/2ad9a895-0558-48e1-af76-a7e42a1eb6fb)

complete conversation:
![Image](https://github.com/user-attachments/assets/ebdfb0f6-621e-4f49-9f56-8e798626e745)

**Logs**
No relevant logs.

**To Reproduce**
Cannot reliably reproduce due to hardware constraints. The provided example took approximately 83 minutes on my system. However, these were the conditions prior to encountering the bug:

Prompted the model "QwQ-32B-GGUF/QwQ-32B-Q6_K.gguf" with:

"Write a Python program that shows a ball bouncing inside a spinning hexagon. The ball should be affected by gravity and friction, and it must bounce off the rotating walls realistically."

Model reasoning extended over 14,000 tokens.

Generation was manually paused multiple times to extend context limits by reloading the model with higher context sizes.

**Expected Behavior**
The UI should automatically exit the "Thinking" state once a </think> tag is processed.

**Comment by ryan-the-crayon** [comment]
Hi. Thanks for the bug report, can you share the config you used for the chat? You can get the config by right clicking the gear next to the model bar, and select copy debug info.

**Comment by Dariton4000** [comment]
### Here is the config for the Chat
````yaml
appVersion: 0.3.11
appBuildVersion: "1"
modelPath: lmstudio-community/QwQ-32B-GGUF/QwQ-32B-Q6_K.gguf
prediction:
  layers:
    - layerName: hardware
      config:
        fields: []
    - layerName: modelDefault
      config:
        fields:
          - key: llm.prediction.promptTemplate
            value: <Default prompt template omitted for brevity>
          - key: llm.prediction.llama.cpuThreads
            value: 9
    - layerName: userModelDefault
      config:
        fields: []
    - layerName: instance
      config:
        fields: []
    - layerName: conversationSpecific
      config:
        fields:
          - key: llm.prediction.speculativeDecoding.draftModel
            value: ""
          - key: llm.prediction.llama.cpuThreads
            value: 12
load:
  layers:
    - layerName: currentlyLoaded
      config:
        fields:
          - key: llm.load.llama.cpuThreadPoolSize
            value: 12
          - key: llm.load.contextLength
            value: 16421
          - key: llm.load.llama.acceleration.offloadRatio
            value: 0.3125
          - key: llm.load.llama.flashAttention
            value: true
    - layerName: instance
      config:
        fields: []
hardware:
  gpuSurveyResult:
    result:
      code: Success
      message: ""
    gpuInfo:
      - name: NVIDIA GeForce RTX 3060
        deviceId: 0
        totalMemoryCapacityBytes: 45808680960
        dedicatedMemoryCapacityBytes: 12703498240
        integrationType: Discrete
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: AMD Radeon(TM) Graphics
        deviceId: 1
        totalMemoryCapacityBytes: 34983641088
        dedicatedMemoryCapacityBytes: 0
        integrationType: Integrated
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
  cpuSurveyResult:
    result:
      code: Success
      message: ""
    cpuInfo:
      name: ""
      architecture: x86_64
      supportedInstructionSetExtensions:
        - AVX
        - AVX2
selectedRuntimes:
  - modelCompatibilityType: gguf
    runtime:
      name: llama.cpp-win-x86_64-nvidia-cuda-avx2
      version: 1.18.0
````

**Comment by ryan-the-crayon** [comment]
@Dariton4000 Thanks for the info. Everything seems correctly, yet we cannot reproduce the issue.

**Comment by Dariton4000** [comment]
Here is my Prompt "Write a Python program that shows a ball bouncing inside a spinning hexagon. The ball should be affected by gravity and friction, and it must bounce off the rotating walls realistically." I did not use any system prompt

**Comment by ryan-the-crayon** [comment]
@Dariton4000 got it, we will try to reproduce.

**Comment by Dariton4000** [comment]
@ryan-the-crayon I was able to reproduce the bug in the newest version of LM-Studio using the same approach as I described in the original Bug Report.

![Image](https://github.com/user-attachments/assets/27672893-8924-4e4b-b021-8da456832900)

I used the same, pausing --> reloading with higher context limit --> continue as before and LM-Studio ignored the same </think> again just like before.

Final Model debug information:
```yaml
appVersion: 0.3.12
appBuildVersion: "1"
modelPath: lmstudio-community/QwQ-32B-GGUF/QwQ-32B-Q6_K.gguf
prediction:
  layers:
    - layerName: hardware
      config:
        fields: []
    - layerName: modelDefault
      config:
        fields:
          - key: llm.prediction.promptTemplate
            value: <Default prompt template omitted for brevity>
          - key: llm.prediction.llama.cpuThreads
            value: 9
    - layerName: userModelDefault
      config:
        fields: []
    - layerName: instance
      config:
        fields: []
    - layerName: conversationSpecific
      config:
        fields:
          - key: llm.prediction.speculativeDecoding.draftModel
            value: ""
          - key: llm.prediction.llama.cpuThreads
            value: 12
load:
  layers:
    - layerName: currentlyLoaded
      config:
        fields:
          - key: llm.load.llama.cpuThreadPoolSize
            value: 12
          - key: llm.load.contextLength
            value: 22270
          - key: llm.load.llama.acceleration.offloadRatio
            value: 0.3125
          - key: llm.load.llama.flashAttention
            value: true
    - layerName: instance
      config:
        fields:
          - key: llm.load.contextLength
            value: 22587
hardware:
  gpuSurveyResult:
    result:
      code: Success
      message: ""
    gpuInfo:
      - name: NVIDIA GeForce RTX 3060
        deviceId: 0
        totalMemoryCapacityBytes: 45808680960
        dedicatedMemoryCapacityBytes: 12703498240
        integrationType: Discrete
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: AMD Radeon(TM) Graphics
        deviceId: 1
        totalMemoryCapacityBytes: 34983641088
        dedicatedMemoryCapacityBytes: 0
        integrationType: Integrated
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
  cpuSurveyResult:
    result:
      code: Success
      message: ""
    cpuInfo:
      name: ""
      architecture: x86_64
      supportedInstructionSetExtensions:
        - AVX
        - AVX2
selectedRuntimes:
  - modelCompatibilityType: gguf
    runtime:
      name: llama.cpp-win-x86_64-nvidia-cuda-avx2
      version: 1.18.0
```
