### ISSUE TITLE
Random EOS token!

### ISSUE THREAD

**Issue by dagazik** [lmstudio-ai/lmstudio-bug-tracker#523]
**Which version of LM Studio?**
LM Studio 0.3.13

**Which operating system?**
Ubuntu 22.04

**What is the bug?**
Random EOS token stops the sequence 2-5 tokens before it is really needed! This happens with any model, but let's take LLAMA 3.2 3b as an example. I don't know when it started, but in new versions of LM Studio, the model's messages end early.

I set top_k 1 and seed 1 to remove randomness.

**Example**

User: who are you?
Model(1st generation): I'm an artificial intelligence model known as Llama. Llama stands for "Large Language
Model(2st generation): I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI
Model(3st generation): I'm an artificial intelligence model known as Llama. Llama stands for "Large Language Model Meta AI."

The sequence stopped correctly only in the last case(3st generation). While generation 1 and generation 2 ended prematurely. I also have an old version of LM studio 0.3.5 and the ending is always correct there.

**To Reproduce**
Just look at the end of the messages.

**Comment by ryan-the-crayon** [comment]
Hi. Thanks for the report. Can you right click the gear and copy model debug info?

![Image](https://github.com/user-attachments/assets/55f0fa47-bfb2-411a-8175-9efcc0695dfa)

**Comment by dagazik** [comment]
Yes, of course! Here is the information:

```yaml
appVersion: 0.3.13
appBuildVersion: "1"
modelPath: hugging-quants/Llama-3.2-3B-Instruct-Q8_0-GGUF/llama-3.2-3b-instruct-q8_0.gguf
prediction:
  layers:
    - layerName: hardware
      config:
        fields: []
    - layerName: modelDefault
      config:
        fields:
          - key: llm.prediction.promptTemplate
            value: <Default prompt template omitted for brevity>
          - key: llm.prediction.llama.cpuThreads
            value: 4
    - layerName: userModelDefault
      config:
        fields: []
    - layerName: instance
      config:
        fields: []
    - layerName: conversationSpecific
      config:
        fields:
          - key: llm.prediction.topKSampling
            value: 1
load:
  layers:
    - layerName: currentlyLoaded
      config:
        fields:
          - key: llm.load.llama.cpuThreadPoolSize
            value: 4
          - key: llm.load.contextLength
            value: 4096
          - key: llm.load.llama.acceleration.offloadRatio
            value: 1
          - key: llm.load.seed
            value:
              checked: true
              value: 1
    - layerName: instance
      config:
        fields: []
hardware:
  gpuSurveyResult:
    result:
      code: Success
      message: ""
    gpuInfo:
      - name: NVIDIA GeForce RTX 3060
        deviceId: 0
        totalMemoryCapacityBytes: 63249027072
        dedicatedMemoryCapacityBytes: 12884901888
        integrationType: Discrete
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: Intel(R) UHD Graphics 730 (ADL-S GT1)
        deviceId: 2
        totalMemoryCapacityBytes: 50364125184
        dedicatedMemoryCapacityBytes: 0
        integrationType: Integrated
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: NVIDIA GeForce RTX 3060
        deviceId: 3
        totalMemoryCapacityBytes: 63249027072
        dedicatedMemoryCapacityBytes: 12884901888
        integrationType: Discrete
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: Intel(R) UHD Graphics 730 (ADL-S GT1)
        deviceId: 5
        totalMemoryCapacityBytes: 50364125184
        dedicatedMemoryCapacityBytes: 0
        integrationType: Integrated
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: NVIDIA GeForce RTX 3060
        deviceId: 6
        totalMemoryCapacityBytes: 63249027072
        dedicatedMemoryCapacityBytes: 12884901888
        integrationType: Discrete
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
      - name: Intel(R) UHD Graphics 730 (ADL-S GT1)
        deviceId: 8
        totalMemoryCapacityBytes: 50364125184
        dedicatedMemoryCapacityBytes: 0
        integrationType: Integrated
        detectionPlatform: Vulkan
        detectionPlatformVersion: 1.3.283
        otherInfo: {}
  cpuSurveyResult:
    result:
      code: Success
      message: ""
    cpuInfo:
      name: ""
      architecture: x86_64
      supportedInstructionSetExtensions:
        - AVX2
        - AVX
selectedRuntimes:
  - modelCompatibilityType: gguf
    runtime:
      name: llama.cpp-linux-x86_64-nvidia-cuda-avx2
      version: 1.21.0
```
