### ISSUE TITLE
There is no separation of the thinking process

### ISSUE THREAD

**Issue by ngocphamm** [lmstudio-ai/lmstudio-bug-tracker#605]
**Which version of LM Studio?**
Example: LM Studio 0.3.14

**Which operating system?**
What is your operating system? macOS 15.4.1

**What is the bug?**
When using `deepseek-r1-distill-qwen-7b` (MLX), the UI doesn't seem to separate the thinking process of the LLM, from its "real" answer.

**Screenshots**
![Image](https://github.com/user-attachments/assets/c1cc1495-4d1a-43c5-852d-6e5c79836ca4)

**Logs**
Add any relevant logs.

**To Reproduce**
1. Download model `mlx-community/DeepSeek-R1-Distill-Qwen-7B-4bit`
2. Ask the model `how to solve Rubik's cube?`
3. See the thinking process of the model being shown, not separated from its answer

**Comment by yagil** [comment]
Hello, did you modify the settings from the default? System prompt or prompt template, specifically. A screenshot of the whole app on the chat page would help

**Comment by ngocphamm** [comment]
@yagil I don't think I modified any of the default settings on system prompt or prompt template.

Here is the screenshot of the whole app. Let me know if you need more information.

![Image](https://github.com/user-attachments/assets/9326047c-3908-40e8-af68-a3e80396642d)

Here's a bit more details on the model default parameters. I don't think I changed any of those.

![Image](https://github.com/user-attachments/assets/0919ad47-0869-4d0b-a216-34c14bdf1c26)

With the Prompt template being below
```
{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% set ns = namespace(is_first=false, is_tool=false, is_output_first=true, system_prompt='') %}{%- for message in messages %}{%- if message['role'] == 'system' %}{% set ns.system_prompt = message['content'] %}{%- endif %}{%- endfor %}{{bos_token}}{{ns.system_prompt}}{%- for message in messages %}{%- if message['role'] == 'user' %}{%- set ns.is_tool = false -%}{{'<｜User｜>' + message['content']}}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is none %}{%- set ns.is_tool = false -%}{%- for tool in message['tool_calls']%}{%- if not ns.is_first %}{{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\n' + '```json' + '\n' + tool['function']['arguments'] + '\n' + '```' + '<｜tool▁call▁end｜>'}}{%- set ns.is_first = true -%}{%- else %}{{'\n' + '<｜tool▁call▁begin｜>' + tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] + '\n' + '```json' + '\n' + tool['function']['arguments'] + '\n' + '```' + '<｜tool▁call▁end｜>'}}{{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>'}}{%- endif %}{%- endfor %}{%- endif %}{%- if message['role'] == 'assistant' and message['content'] is not none %}{%- if ns.is_tool %}{{'<｜tool▁outputs▁end｜>' + message['content'] + '<｜end▁of▁sentence｜>'}}{%- set ns.is_tool = false -%}{%- else %}{% set content = message['content'] %}{% if '</think>' in content %}{% set content = content.split('</think>')|last %}{% endif %}{{'<｜Assistant｜>' + content + '<｜end▁of▁sentence｜>'}}{%- endif %}{%- endif %}{%- if message['role'] == 'tool' %}{%- set ns.is_tool = true -%}{%- if ns.is_output_first %}{{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- set ns.is_output_first = false %}{%- else %}{{'\n<｜tool▁output▁begin｜>' + message['content'] + '<｜tool▁output▁end｜>'}}{%- endif %}{%- endif %}{%- endfor -%}{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜>'}}{% endif %}{% if add_generation_prompt and not ns.is_tool %}{{'<｜Assistant｜><think>\n'}}{% endif %}
```

**Comment by ryan-the-crayon** [comment]
This prompt template is not setup correctly. Please remove the `<think>` from it.

Short explanation: the prompt template injects the <think> token. As a result, the model did not actually start "thinking".

**Comment by ngocphamm** [comment]
@ryan-the-crayon Where exactly do you mean?

If you meant the one near the end of the Prompt Template, then I tried but it didn't seem to help. Load the model, ask the question, and still see the thinking.

`...{{'<｜Assistant｜>\n'}}{% endif %}`

**Comment by ryan-the-crayon** [comment]
@ngocphamm Can you copy the model debug information? I suspect you have prompt template override somewhere. Thanks.

![Image](https://github.com/user-attachments/assets/b821d090-63fa-4075-830e-fb3fc91ee814)

**Comment by ngocphamm** [comment]
@ryan-the-crayon Here it is.

I don't remember changing any prompt template but I might have clicked something accidentally. I just tried out LM Studio for about 2 days now.

```yaml
appVersion: 0.3.14
appBuildVersion: "5"
modelPath: mlx-community/DeepSeek-R1-Distill-Qwen-7B-4bit
prediction:
  layers:
    - layerName: hardware
      config:
        fields: []
    - layerName: modelDefault
      config:
        fields:
          - key: llm.prediction.promptTemplate
            value: <Default prompt template omitted for brevity>
          - key: llm.prediction.llama.cpuThreads
            value: 7
          - key: llm.prediction.topPSampling
            value:
              checked: false
              value: 1
          - key: llm.prediction.minPSampling
            value:
              checked: false
              value: 0
          - key: llm.prediction.repeatPenalty
            value:
              checked: true
              value: 1.1
    - layerName: userModelDefault
      config:
        fields:
          - key: llm.prediction.promptTemplate
            value:
              type: jinja
              jinjaPromptTemplate:
                template: "{% if not add_generation_prompt is defined %}{% set
                  add_generation_prompt = false %}{% endif %}{% set ns =
                  namespace(is_first=false, is_tool=false, is_output_first=true,
                  system_prompt='') %}{%- for message in messages %}{%- if
                  message['role'] == 'system' %}{% set ns.system_prompt =
                  message['content'] %}{%- endif %}{%- endfor
                  %}{{bos_token}}{{ns.system_prompt}}{%- for message in messages
                  %}{%- if message['role'] == 'user' %}{%- set ns.is_tool =
                  false -%}{{'<｜User｜>' + message['content']}}{%- endif %}{%- if
                  message['role'] == 'assistant' and message['content'] is none
                  %}{%- set ns.is_tool = false -%}{%- for tool in
                  message['tool_calls']%}{%- if not ns.is_first
                  %}{{'<｜Assistant｜><｜tool▁calls▁begin｜><｜tool▁call▁begin｜>' +
                  tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] +
                  '\\n' + '```json' + '\\n' + tool['function']['arguments'] +
                  '\\n' + '```' + '<｜tool▁call▁end｜>'}}{%- set ns.is_first =
                  true -%}{%- else %}{{'\\n' + '<｜tool▁call▁begin｜>' +
                  tool['type'] + '<｜tool▁sep｜>' + tool['function']['name'] +
                  '\\n' + '```json' + '\\n' + tool['function']['arguments'] +
                  '\\n' + '```' +
                  '<｜tool▁call▁end｜>'}}{{'<｜tool▁calls▁end｜><｜end▁of▁sentence｜>\
                  '}}{%- endif %}{%- endfor %}{%- endif %}{%- if message['role']
                  == 'assistant' and message['content'] is not none %}{%- if
                  ns.is_tool %}{{'<｜tool▁outputs▁end｜>' + message['content'] +
                  '<｜end▁of▁sentence｜>'}}{%- set ns.is_tool = false -%}{%- else
                  %}{% set content = message['content'] %}{% if '</think>' in
                  content %}{% set content = content.split('</think>')|last %}{%
                  endif %}{{'<｜Assistant｜>' + content +
                  '<｜end▁of▁sentence｜>'}}{%- endif %}{%- endif %}{%- if
                  message['role'] == 'tool' %}{%- set ns.is_tool = true -%}{%-
                  if ns.is_output_first
                  %}{{'<｜tool▁outputs▁begin｜><｜tool▁output▁begin｜>' +
                  message['content'] + '<｜tool▁output▁end｜>'}}{%- set
                  ns.is_output_first = false %}{%- else
                  %}{{'\\n<｜tool▁output▁begin｜>' + message['content'] +
                  '<｜tool▁output▁end｜>'}}{%- endif %}{%- endif %}{%- endfor
                  -%}{% if ns.is_tool %}{{'<｜tool▁outputs▁end｜>'}}{% endif %}{%
                  if add_generation_prompt and not ns.is_tool
                  %}{{'<｜Assistant｜>\\n'}}{% endif %}"
                bosToken: <｜begin▁of▁sentence｜>
                eosToken: <｜end▁of▁sentence｜>
                inputConfig:
                  messagesConfig:
                    contentConfig:
                      type: string
                  useTools: false
              stopStrings: []
    - layerName: instance
      config:
        fields: []
    - layerName: conversationSpecific
      config:
        fields: []
load:
  layers:
    - layerName: currentlyLoaded
      config:
        fields:
          - key: llm.load.llama.cpuThreadPoolSize
            value: 7
          - key: llm.load.contextLength
            value: 131072
    - layerName: instance
      config:
        fields: []
hardware:
  gpuSurveyResult:
    result:
      code: Success
      message: Successfully queried Apple Silicon for GPU Info.
    gpuInfo:
      - name: Apple Silicon
        deviceId: 0
        totalMemoryCapacityBytes: 34359738368
        dedicatedMemoryCapacityBytes: 22906503168
        integrationType: Integrated
        detectionPlatform: Metal
        detectionPlatformVersion: ""
        otherInfo: {}
  cpuSurveyResult:
    result:
      code: Success
      message: ""
    cpuInfo:
      name: Apple M1 Max
      architecture: ARM64
      supportedInstructionSetExtensions:
        - AdvSIMD
selectedRuntimes:
  - modelCompatibilityType: gguf
    runtime:
      name: llama.cpp-mac-arm64-apple-metal-advsimd
      version: 1.26.0
  - modelCompatibilityType: safetensors
    runtime:
      name: mlx-llm-mac-arm64-apple-metal-advsimd
      version: 0.13.2
```
